# [2016-10-03] Auto-generated file, do not edit

PRODUCT_COPY_FILES += \
    vendor/lge/bullhead/proprietary/bin/ATFWD-daemon:$(TARGET_COPY_OUT_SYSTEM)/bin/ATFWD-daemon:lge \
    vendor/lge/bullhead/proprietary/bin/btnvtool:$(TARGET_COPY_OUT_SYSTEM)/bin/btnvtool:lge \
    vendor/lge/bullhead/proprietary/bin/cnd:$(TARGET_COPY_OUT_SYSTEM)/bin/cnd:lge \
    vendor/lge/bullhead/proprietary/bin/cnss-daemon:$(TARGET_COPY_OUT_SYSTEM)/bin/cnss-daemon:lge \
    vendor/lge/bullhead/proprietary/bin/diag_klog:$(TARGET_COPY_OUT_SYSTEM)/bin/diag_klog:lge \
    vendor/lge/bullhead/proprietary/bin/diag_mdlog:$(TARGET_COPY_OUT_SYSTEM)/bin/diag_mdlog:lge \
    vendor/lge/bullhead/proprietary/bin/fingerprintd:$(TARGET_COPY_OUT_SYSTEM)/bin/fingerprintd:lge \
    vendor/lge/bullhead/proprietary/bin/imsdatadaemon:$(TARGET_COPY_OUT_SYSTEM)/bin/imsdatadaemon:lge \
    vendor/lge/bullhead/proprietary/bin/imsqmidaemon:$(TARGET_COPY_OUT_SYSTEM)/bin/imsqmidaemon:lge \
    vendor/lge/bullhead/proprietary/bin/ims_rtp_daemon:$(TARGET_COPY_OUT_SYSTEM)/bin/ims_rtp_daemon:lge \
    vendor/lge/bullhead/proprietary/bin/irsc_util:$(TARGET_COPY_OUT_SYSTEM)/bin/irsc_util:lge \
    vendor/lge/bullhead/proprietary/bin/location-mq:$(TARGET_COPY_OUT_SYSTEM)/bin/location-mq:lge \
    vendor/lge/bullhead/proprietary/bin/loc_launcher:$(TARGET_COPY_OUT_SYSTEM)/bin/loc_launcher:lge \
    vendor/lge/bullhead/proprietary/bin/lowi-server:$(TARGET_COPY_OUT_SYSTEM)/bin/lowi-server:lge \
    vendor/lge/bullhead/proprietary/bin/mm-qcamera-app:$(TARGET_COPY_OUT_SYSTEM)/bin/mm-qcamera-app:lge \
    vendor/lge/bullhead/proprietary/bin/msm_irqbalance:$(TARGET_COPY_OUT_SYSTEM)/bin/msm_irqbalance:lge \
    vendor/lge/bullhead/proprietary/bin/netmgrd:$(TARGET_COPY_OUT_SYSTEM)/bin/netmgrd:lge \
    vendor/lge/bullhead/proprietary/bin/nl_listener:$(TARGET_COPY_OUT_SYSTEM)/bin/nl_listener:lge \
    vendor/lge/bullhead/proprietary/bin/perfd:$(TARGET_COPY_OUT_SYSTEM)/bin/perfd:lge \
    vendor/lge/bullhead/proprietary/bin/pm-proxy:$(TARGET_COPY_OUT_SYSTEM)/bin/pm-proxy:lge \
    vendor/lge/bullhead/proprietary/bin/pm-service:$(TARGET_COPY_OUT_SYSTEM)/bin/pm-service:lge \
    vendor/lge/bullhead/proprietary/bin/port-bridge:$(TARGET_COPY_OUT_SYSTEM)/bin/port-bridge:lge \
    vendor/lge/bullhead/proprietary/bin/qmakernote-xtract:$(TARGET_COPY_OUT_SYSTEM)/bin/qmakernote-xtract:lge \
    vendor/lge/bullhead/proprietary/bin/qmuxd:$(TARGET_COPY_OUT_SYSTEM)/bin/qmuxd:lge \
    vendor/lge/bullhead/proprietary/bin/radish:$(TARGET_COPY_OUT_SYSTEM)/bin/radish:lge \
    vendor/lge/bullhead/proprietary/bin/rmt_storage:$(TARGET_COPY_OUT_SYSTEM)/bin/rmt_storage:lge \
    vendor/lge/bullhead/proprietary/bin/service:$(TARGET_COPY_OUT_SYSTEM)/bin/service:lge \
    vendor/lge/bullhead/proprietary/bin/servicemanager:$(TARGET_COPY_OUT_SYSTEM)/bin/servicemanager:lge \
    vendor/lge/bullhead/proprietary/bin/subsystem_ramdump:$(TARGET_COPY_OUT_SYSTEM)/bin/subsystem_ramdump:lge \
    vendor/lge/bullhead/proprietary/bin/thermal-engine:$(TARGET_COPY_OUT_SYSTEM)/bin/thermal-engine:lge \
    vendor/lge/bullhead/proprietary/bin/time_daemon:$(TARGET_COPY_OUT_SYSTEM)/bin/time_daemon:lge \
    vendor/lge/bullhead/proprietary/bin/wcnss_filter:$(TARGET_COPY_OUT_SYSTEM)/bin/wcnss_filter:lge \
    vendor/lge/bullhead/proprietary/etc/acdbdata/MTP/MTP_Bluetooth_cal.acdb:$(TARGET_COPY_OUT_SYSTEM)/etc/acdbdata/MTP/MTP_Bluetooth_cal.acdb:lge \
    vendor/lge/bullhead/proprietary/etc/acdbdata/MTP/MTP_General_cal.acdb:$(TARGET_COPY_OUT_SYSTEM)/etc/acdbdata/MTP/MTP_General_cal.acdb:lge \
    vendor/lge/bullhead/proprietary/etc/acdbdata/MTP/MTP_Global_cal.acdb:$(TARGET_COPY_OUT_SYSTEM)/etc/acdbdata/MTP/MTP_Global_cal.acdb:lge \
    vendor/lge/bullhead/proprietary/etc/acdbdata/MTP/MTP_Handset_cal.acdb:$(TARGET_COPY_OUT_SYSTEM)/etc/acdbdata/MTP/MTP_Handset_cal.acdb:lge \
    vendor/lge/bullhead/proprietary/etc/acdbdata/MTP/MTP_Hdmi_cal.acdb:$(TARGET_COPY_OUT_SYSTEM)/etc/acdbdata/MTP/MTP_Hdmi_cal.acdb:lge \
    vendor/lge/bullhead/proprietary/etc/acdbdata/MTP/MTP_Headset_cal.acdb:$(TARGET_COPY_OUT_SYSTEM)/etc/acdbdata/MTP/MTP_Headset_cal.acdb:lge \
    vendor/lge/bullhead/proprietary/etc/acdbdata/MTP/MTP_Speaker_cal.acdb:$(TARGET_COPY_OUT_SYSTEM)/etc/acdbdata/MTP/MTP_Speaker_cal.acdb:lge \
    vendor/lge/bullhead/proprietary/etc/cne/profile.txt:$(TARGET_COPY_OUT_SYSTEM)/etc/cne/profile.txt:lge \
    vendor/lge/bullhead/proprietary/etc/data/dsi_config.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/data/dsi_config.xml:lge \
    vendor/lge/bullhead/proprietary/etc/data/netmgr_config.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/data/netmgr_config.xml:lge \
    vendor/lge/bullhead/proprietary/etc/data/qmi_config.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/data/qmi_config.xml:lge \
    vendor/lge/bullhead/proprietary/etc/diag/Bullhead_radio-general.cfg:$(TARGET_COPY_OUT_SYSTEM)/etc/diag/Bullhead_radio-general.cfg:lge \
    vendor/lge/bullhead/proprietary/etc/diag/ims_epdg.cfg:$(TARGET_COPY_OUT_SYSTEM)/etc/diag/ims_epdg.cfg:lge \
    vendor/lge/bullhead/proprietary/etc/diag/wlan.cfg:$(TARGET_COPY_OUT_SYSTEM)/etc/diag/wlan.cfg:lge \
    vendor/lge/bullhead/proprietary/etc/flp.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/flp.conf:lge \
    vendor/lge/bullhead/proprietary/etc/izat.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/izat.conf:lge \
    vendor/lge/bullhead/proprietary/etc/lowi.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/lowi.conf:lge \
    vendor/lge/bullhead/proprietary/etc/old-apns-conf.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/old-apns-conf.xml:lge \
    vendor/lge/bullhead/proprietary/etc/permissions/cneapiclient.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/permissions/cneapiclient.xml:lge \
    vendor/lge/bullhead/proprietary/etc/permissions/com.android.omadm.service.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/permissions/com.android.omadm.service.xml:lge \
    vendor/lge/bullhead/proprietary/etc/permissions/qcrilhook.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/permissions/qcrilhook.xml:lge \
    vendor/lge/bullhead/proprietary/etc/permissions/qti_permissions.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/permissions/qti_permissions.xml:lge \
    vendor/lge/bullhead/proprietary/etc/permissions/rcsservice.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/permissions/rcsservice.xml:lge \
    vendor/lge/bullhead/proprietary/etc/qcril.db:$(TARGET_COPY_OUT_SYSTEM)/etc/qcril.db:lge \
    vendor/lge/bullhead/proprietary/etc/sap.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/sap.conf:lge \
    vendor/lge/bullhead/proprietary/etc/sysconfig/whitelist_com.android.omadm.service.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/sysconfig/whitelist_com.android.omadm.service.xml:lge \
    vendor/lge/bullhead/proprietary/etc/thermal-engine-8992.conf:$(TARGET_COPY_OUT_SYSTEM)/etc/thermal-engine-8992.conf:lge \
    vendor/lge/bullhead/proprietary/lib64/hw/audio.primary.msm8992.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/hw/audio.primary.msm8992.so:lge \
    vendor/lge/bullhead/proprietary/lib64/hw/fingerprint.bullhead.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/hw/fingerprint.bullhead.so:lge \
    vendor/lge/bullhead/proprietary/lib64/hw/gps.msm8992.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/hw/gps.msm8992.so:lge \
    vendor/lge/bullhead/proprietary/lib64/hw/nfc_nci.bullhead.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/hw/nfc_nci.bullhead.so:lge \
    vendor/lge/bullhead/proprietary/lib64/lib_fpc_tac_shared.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/lib_fpc_tac_shared.so:lge \
    vendor/lge/bullhead/proprietary/lib64/libgps.utils.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libgps.utils.so:lge \
    vendor/lge/bullhead/proprietary/lib64/libloc_core.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libloc_core.so:lge \
    vendor/lge/bullhead/proprietary/lib64/libloc_eng.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libloc_eng.so:lge \
    vendor/lge/bullhead/proprietary/lib/hw/audio.primary.msm8992.so:$(TARGET_COPY_OUT_SYSTEM)/lib/hw/audio.primary.msm8992.so:lge \
    vendor/lge/bullhead/proprietary/lib/hw/camera.msm8992.so:$(TARGET_COPY_OUT_SYSTEM)/lib/hw/camera.msm8992.so:lge \
    vendor/lge/bullhead/proprietary/lib/hw/fingerprint.bullhead.so:$(TARGET_COPY_OUT_SYSTEM)/lib/hw/fingerprint.bullhead.so:lge \
    vendor/lge/bullhead/proprietary/lib/hw/gps.msm8992.so:$(TARGET_COPY_OUT_SYSTEM)/lib/hw/gps.msm8992.so:lge \
    vendor/lge/bullhead/proprietary/lib/hw/local_time.default.so:$(TARGET_COPY_OUT_SYSTEM)/lib/hw/local_time.default.so:lge \
    vendor/lge/bullhead/proprietary/lib/hw/nfc_nci.bullhead.so:$(TARGET_COPY_OUT_SYSTEM)/lib/hw/nfc_nci.bullhead.so:lge \
    vendor/lge/bullhead/proprietary/lib/libdmengine.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libdmengine.so:lge \
    vendor/lge/bullhead/proprietary/lib/libdmjavaplugin.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libdmjavaplugin.so:lge \
    vendor/lge/bullhead/proprietary/lib/lib_fpc_tac_shared.so:$(TARGET_COPY_OUT_SYSTEM)/lib/lib_fpc_tac_shared.so:lge \
    vendor/lge/bullhead/proprietary/lib/libgps.utils.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libgps.utils.so:lge \
    vendor/lge/bullhead/proprietary/lib/libloc_core.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libloc_core.so:lge \
    vendor/lge/bullhead/proprietary/lib/libloc_eng.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libloc_eng.so:lge \
    vendor/lge/bullhead/proprietary/lib/libmmcamera_interface.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libmmcamera_interface.so:lge \
    vendor/lge/bullhead/proprietary/lib/libmmjpeg_interface.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libmmjpeg_interface.so:lge \
    vendor/lge/bullhead/proprietary/lib/libqomx_core.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libqomx_core.so:lge \
    vendor/lge/bullhead/proprietary/lib/soundfx/libfmas.so:$(TARGET_COPY_OUT_SYSTEM)/lib/soundfx/libfmas.so:lge \
    vendor/lge/bullhead/vendor/bin/mm-qcamera-daemon:$(TARGET_COPY_OUT_VENDOR)/bin/mm-qcamera-daemon:lge \
    vendor/lge/bullhead/vendor/bin/qseecomd:$(TARGET_COPY_OUT_VENDOR)/bin/qseecomd:lge \
    vendor/lge/bullhead/vendor/bin/qti:$(TARGET_COPY_OUT_VENDOR)/bin/qti:lge \
    vendor/lge/bullhead/vendor/bin/slim_daemon:$(TARGET_COPY_OUT_VENDOR)/bin/slim_daemon:lge \
    vendor/lge/bullhead/vendor/etc/audio_effects.conf:$(TARGET_COPY_OUT_VENDOR)/etc/audio_effects.conf:lge \
    vendor/lge/bullhead/vendor/etc/msm_irqbalance.conf:$(TARGET_COPY_OUT_VENDOR)/etc/msm_irqbalance.conf:lge \
    vendor/lge/bullhead/vendor/etc/perf-profile0.conf:$(TARGET_COPY_OUT_VENDOR)/etc/perf-profile0.conf:lge \
    vendor/lge/bullhead/vendor/firmware/a420_pfp.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/a420_pfp.fw:lge \
    vendor/lge/bullhead/vendor/firmware/a420_pm4.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/a420_pm4.fw:lge \
    vendor/lge/bullhead/vendor/firmware/activity.napp:$(TARGET_COPY_OUT_VENDOR)/firmware/activity.napp:lge \
    vendor/lge/bullhead/vendor/firmware/adsp.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/adsp.b00:lge \
    vendor/lge/bullhead/vendor/firmware/adsp.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/adsp.b01:lge \
    vendor/lge/bullhead/vendor/firmware/adsp.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/adsp.b02:lge \
    vendor/lge/bullhead/vendor/firmware/adsp.b03:$(TARGET_COPY_OUT_VENDOR)/firmware/adsp.b03:lge \
    vendor/lge/bullhead/vendor/firmware/adsp.b04:$(TARGET_COPY_OUT_VENDOR)/firmware/adsp.b04:lge \
    vendor/lge/bullhead/vendor/firmware/adsp.b05:$(TARGET_COPY_OUT_VENDOR)/firmware/adsp.b05:lge \
    vendor/lge/bullhead/vendor/firmware/adsp.b06:$(TARGET_COPY_OUT_VENDOR)/firmware/adsp.b06:lge \
    vendor/lge/bullhead/vendor/firmware/adsp.b07:$(TARGET_COPY_OUT_VENDOR)/firmware/adsp.b07:lge \
    vendor/lge/bullhead/vendor/firmware/adsp.b08:$(TARGET_COPY_OUT_VENDOR)/firmware/adsp.b08:lge \
    vendor/lge/bullhead/vendor/firmware/adsp.b09:$(TARGET_COPY_OUT_VENDOR)/firmware/adsp.b09:lge \
    vendor/lge/bullhead/vendor/firmware/adsp.b10:$(TARGET_COPY_OUT_VENDOR)/firmware/adsp.b10:lge \
    vendor/lge/bullhead/vendor/firmware/adsp.b11:$(TARGET_COPY_OUT_VENDOR)/firmware/adsp.b11:lge \
    vendor/lge/bullhead/vendor/firmware/adsp.b12:$(TARGET_COPY_OUT_VENDOR)/firmware/adsp.b12:lge \
    vendor/lge/bullhead/vendor/firmware/adsp.b13:$(TARGET_COPY_OUT_VENDOR)/firmware/adsp.b13:lge \
    vendor/lge/bullhead/vendor/firmware/adsp.b14:$(TARGET_COPY_OUT_VENDOR)/firmware/adsp.b14:lge \
    vendor/lge/bullhead/vendor/firmware/adsp.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/adsp.mdt:lge \
    vendor/lge/bullhead/vendor/firmware/bdwlan30.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/bdwlan30.bin:lge \
    vendor/lge/bullhead/vendor/firmware/btfw32.tlv:$(TARGET_COPY_OUT_VENDOR)/firmware/btfw32.tlv:lge \
    vendor/lge/bullhead/vendor/firmware/btnv32.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/btnv32.bin:lge \
    vendor/lge/bullhead/vendor/firmware/cpe.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/cpe.b02:lge \
    vendor/lge/bullhead/vendor/firmware/cpe.b04:$(TARGET_COPY_OUT_VENDOR)/firmware/cpe.b04:lge \
    vendor/lge/bullhead/vendor/firmware/cpe.b05:$(TARGET_COPY_OUT_VENDOR)/firmware/cpe.b05:lge \
    vendor/lge/bullhead/vendor/firmware/cpe.b06:$(TARGET_COPY_OUT_VENDOR)/firmware/cpe.b06:lge \
    vendor/lge/bullhead/vendor/firmware/cpe.b08:$(TARGET_COPY_OUT_VENDOR)/firmware/cpe.b08:lge \
    vendor/lge/bullhead/vendor/firmware/cpe.b10:$(TARGET_COPY_OUT_VENDOR)/firmware/cpe.b10:lge \
    vendor/lge/bullhead/vendor/firmware/cpe.b11:$(TARGET_COPY_OUT_VENDOR)/firmware/cpe.b11:lge \
    vendor/lge/bullhead/vendor/firmware/cpe.b12:$(TARGET_COPY_OUT_VENDOR)/firmware/cpe.b12:lge \
    vendor/lge/bullhead/vendor/firmware/cpe.b14:$(TARGET_COPY_OUT_VENDOR)/firmware/cpe.b14:lge \
    vendor/lge/bullhead/vendor/firmware/cpe.b16:$(TARGET_COPY_OUT_VENDOR)/firmware/cpe.b16:lge \
    vendor/lge/bullhead/vendor/firmware/cpe.b18:$(TARGET_COPY_OUT_VENDOR)/firmware/cpe.b18:lge \
    vendor/lge/bullhead/vendor/firmware/cpe.b20:$(TARGET_COPY_OUT_VENDOR)/firmware/cpe.b20:lge \
    vendor/lge/bullhead/vendor/firmware/cpe.b21:$(TARGET_COPY_OUT_VENDOR)/firmware/cpe.b21:lge \
    vendor/lge/bullhead/vendor/firmware/cpe.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/cpe.mdt:lge \
    vendor/lge/bullhead/vendor/firmware/cpp_firmware_v1_1_1.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_1_1.fw:lge \
    vendor/lge/bullhead/vendor/firmware/cpp_firmware_v1_1_6.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_1_6.fw:lge \
    vendor/lge/bullhead/vendor/firmware/cpp_firmware_v1_2_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_2_0.fw:lge \
    vendor/lge/bullhead/vendor/firmware/cpp_firmware_v1_4_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_4_0.fw:lge \
    vendor/lge/bullhead/vendor/firmware/cpp_firmware_v1_6_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_6_0.fw:lge \
    vendor/lge/bullhead/vendor/firmware/cpp_firmware_v1_8_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_8_0.fw:lge \
    vendor/lge/bullhead/vendor/firmware/Data.msc:$(TARGET_COPY_OUT_VENDOR)/firmware/Data.msc:lge \
    vendor/lge/bullhead/vendor/firmware/double_twist.napp:$(TARGET_COPY_OUT_VENDOR)/firmware/double_twist.napp:lge \
    vendor/lge/bullhead/vendor/firmware/fpctzappfingerprint.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/fpctzappfingerprint.b00:lge \
    vendor/lge/bullhead/vendor/firmware/fpctzappfingerprint.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/fpctzappfingerprint.b01:lge \
    vendor/lge/bullhead/vendor/firmware/fpctzappfingerprint.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/fpctzappfingerprint.b02:lge \
    vendor/lge/bullhead/vendor/firmware/fpctzappfingerprint.b03:$(TARGET_COPY_OUT_VENDOR)/firmware/fpctzappfingerprint.b03:lge \
    vendor/lge/bullhead/vendor/firmware/fpctzappfingerprint.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/fpctzappfingerprint.mdt:lge \
    vendor/lge/bullhead/vendor/firmware/leia_pfp_470.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/leia_pfp_470.fw:lge \
    vendor/lge/bullhead/vendor/firmware/leia_pm4_470.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/leia_pm4_470.fw:lge \
    vendor/lge/bullhead/vendor/firmware/libpn548ad_fw.so:$(TARGET_COPY_OUT_VENDOR)/firmware/libpn548ad_fw.so:lge \
    vendor/lge/bullhead/vendor/firmware/nanohub.full.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/nanohub.full.bin:lge \
    vendor/lge/bullhead/vendor/firmware/napp_list.cfg:$(TARGET_COPY_OUT_VENDOR)/firmware/napp_list.cfg:lge \
    vendor/lge/bullhead/vendor/firmware/otp30.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/otp30.bin:lge \
    vendor/lge/bullhead/vendor/firmware/pickup_gesture.napp:$(TARGET_COPY_OUT_VENDOR)/firmware/pickup_gesture.napp:lge \
    vendor/lge/bullhead/vendor/firmware/qwlan30.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/qwlan30.bin:lge \
    vendor/lge/bullhead/vendor/firmware/sig_motion.napp:$(TARGET_COPY_OUT_VENDOR)/firmware/sig_motion.napp:lge \
    vendor/lge/bullhead/vendor/firmware/synaptics_fw.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/synaptics_fw.bin:lge \
    vendor/lge/bullhead/vendor/firmware/utf30.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/utf30.bin:lge \
    vendor/lge/bullhead/vendor/firmware/venus.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/venus.b00:lge \
    vendor/lge/bullhead/vendor/firmware/venus.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/venus.b01:lge \
    vendor/lge/bullhead/vendor/firmware/venus.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/venus.b02:lge \
    vendor/lge/bullhead/vendor/firmware/venus.b03:$(TARGET_COPY_OUT_VENDOR)/firmware/venus.b03:lge \
    vendor/lge/bullhead/vendor/firmware/venus.b04:$(TARGET_COPY_OUT_VENDOR)/firmware/venus.b04:lge \
    vendor/lge/bullhead/vendor/firmware/venus.mbn:$(TARGET_COPY_OUT_VENDOR)/firmware/venus.mbn:lge \
    vendor/lge/bullhead/vendor/firmware/venus.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/venus.mdt:lge \
    vendor/lge/bullhead/vendor/firmware/widevine.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/widevine.b00:lge \
    vendor/lge/bullhead/vendor/firmware/widevine.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/widevine.b01:lge \
    vendor/lge/bullhead/vendor/firmware/widevine.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/widevine.b02:lge \
    vendor/lge/bullhead/vendor/firmware/widevine.b03:$(TARGET_COPY_OUT_VENDOR)/firmware/widevine.b03:lge \
    vendor/lge/bullhead/vendor/firmware/widevine.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/widevine.mdt:lge \
    vendor/lge/bullhead/vendor/lib64/egl/eglSubDriverAndroid.so:$(TARGET_COPY_OUT_VENDOR)/lib64/egl/eglSubDriverAndroid.so:lge \
    vendor/lge/bullhead/vendor/lib64/egl/libEGL_adreno.so:$(TARGET_COPY_OUT_VENDOR)/lib64/egl/libEGL_adreno.so:lge \
    vendor/lge/bullhead/vendor/lib64/egl/libGLESv1_CM_adreno.so:$(TARGET_COPY_OUT_VENDOR)/lib64/egl/libGLESv1_CM_adreno.so:lge \
    vendor/lge/bullhead/vendor/lib64/egl/libGLESv2_adreno.so:$(TARGET_COPY_OUT_VENDOR)/lib64/egl/libGLESv2_adreno.so:lge \
    vendor/lge/bullhead/vendor/lib64/egl/libq3dtools_adreno.so:$(TARGET_COPY_OUT_VENDOR)/lib64/egl/libq3dtools_adreno.so:lge \
    vendor/lge/bullhead/vendor/lib64/egl/libq3dtools_esx.so:$(TARGET_COPY_OUT_VENDOR)/lib64/egl/libq3dtools_esx.so:lge \
    vendor/lge/bullhead/vendor/lib64/hw/flp.default.so:$(TARGET_COPY_OUT_VENDOR)/lib64/hw/flp.default.so:lge \
    vendor/lge/bullhead/vendor/lib64/hw/gatekeeper.msm8992.so:$(TARGET_COPY_OUT_VENDOR)/lib64/hw/gatekeeper.msm8992.so:lge \
    vendor/lge/bullhead/vendor/lib64/hw/keystore.msm8992.so:$(TARGET_COPY_OUT_VENDOR)/lib64/hw/keystore.msm8992.so:lge \
    vendor/lge/bullhead/vendor/lib64/hw/sound_trigger.primary.msm8992.so:$(TARGET_COPY_OUT_VENDOR)/lib64/hw/sound_trigger.primary.msm8992.so:lge \
    vendor/lge/bullhead/vendor/lib64/hw/vulkan.msm8992.so:$(TARGET_COPY_OUT_VENDOR)/lib64/hw/vulkan.msm8992.so:lge \
    vendor/lge/bullhead/vendor/lib64/libacdb-fts.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libacdb-fts.so:lge \
    vendor/lge/bullhead/vendor/lib64/libacdbloader.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libacdbloader.so:lge \
    vendor/lge/bullhead/vendor/lib64/libacdbmapper.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libacdbmapper.so:lge \
    vendor/lge/bullhead/vendor/lib64/libacdbrtac.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libacdbrtac.so:lge \
    vendor/lge/bullhead/vendor/lib64/libadiertac.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libadiertac.so:lge \
    vendor/lge/bullhead/vendor/lib64/libadreno_utils.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libadreno_utils.so:lge \
    vendor/lge/bullhead/vendor/lib64/libadsprpc.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libadsprpc.so:lge \
    vendor/lge/bullhead/vendor/lib64/libaudcal.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libaudcal.so:lge \
    vendor/lge/bullhead/vendor/lib64/libaudioalsa.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libaudioalsa.so:lge \
    vendor/lge/bullhead/vendor/lib64/libbccQTI.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libbccQTI.so:lge \
    vendor/lge/bullhead/vendor/lib64/libbtnv.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libbtnv.so:lge \
    vendor/lge/bullhead/vendor/lib64/libC2D2.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libC2D2.so:lge \
    vendor/lge/bullhead/vendor/lib64/libc2d30-a3xx.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libc2d30-a3xx.so:lge \
    vendor/lge/bullhead/vendor/lib64/libc2d30-a4xx.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libc2d30-a4xx.so:lge \
    vendor/lge/bullhead/vendor/lib64/libCB.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libCB.so:lge \
    vendor/lge/bullhead/vendor/lib64/libcneapiclient.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libcneapiclient.so:lge \
    vendor/lge/bullhead/vendor/lib64/libcne.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libcne.so:lge \
    vendor/lge/bullhead/vendor/lib64/libCommandSvc.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libCommandSvc.so:lge \
    vendor/lge/bullhead/vendor/lib64/libconfigdb.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libconfigdb.so:lge \
    vendor/lge/bullhead/vendor/lib64/libdiag.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libdiag.so:lge \
    vendor/lge/bullhead/vendor/lib64/lib-dplmedia.so:$(TARGET_COPY_OUT_VENDOR)/lib64/lib-dplmedia.so:lge \
    vendor/lge/bullhead/vendor/lib64/libdrmfs.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libdrmfs.so:lge \
    vendor/lge/bullhead/vendor/lib64/libdrmtime.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libdrmtime.so:lge \
    vendor/lge/bullhead/vendor/lib64/libdsutils.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libdsutils.so:lge \
    vendor/lge/bullhead/vendor/lib64/libEGL_adreno.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libEGL_adreno.so:lge \
    vendor/lge/bullhead/vendor/lib64/libfrsdk.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libfrsdk.so:lge \
    vendor/lge/bullhead/vendor/lib64/libgeofence.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libgeofence.so:lge \
    vendor/lge/bullhead/vendor/lib64/libgsl.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libgsl.so:lge \
    vendor/lge/bullhead/vendor/lib64/libidl.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libidl.so:lge \
    vendor/lge/bullhead/vendor/lib64/libimscamera_jni.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libimscamera_jni.so:lge \
    vendor/lge/bullhead/vendor/lib64/lib-imsdpl.so:$(TARGET_COPY_OUT_VENDOR)/lib64/lib-imsdpl.so:lge \
    vendor/lge/bullhead/vendor/lib64/libimsmedia_jni.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libimsmedia_jni.so:lge \
    vendor/lge/bullhead/vendor/lib64/lib-imsqimf.so:$(TARGET_COPY_OUT_VENDOR)/lib64/lib-imsqimf.so:lge \
    vendor/lge/bullhead/vendor/lib64/lib-imsrcscmclient.so:$(TARGET_COPY_OUT_VENDOR)/lib64/lib-imsrcscmclient.so:lge \
    vendor/lge/bullhead/vendor/lib64/lib-ims-rcscmjni.so:$(TARGET_COPY_OUT_VENDOR)/lib64/lib-ims-rcscmjni.so:lge \
    vendor/lge/bullhead/vendor/lib64/lib-imsrcscmservice.so:$(TARGET_COPY_OUT_VENDOR)/lib64/lib-imsrcscmservice.so:lge \
    vendor/lge/bullhead/vendor/lib64/lib-imsrcscm.so:$(TARGET_COPY_OUT_VENDOR)/lib64/lib-imsrcscm.so:lge \
    vendor/lge/bullhead/vendor/lib64/lib-imsrcs.so:$(TARGET_COPY_OUT_VENDOR)/lib64/lib-imsrcs.so:lge \
    vendor/lge/bullhead/vendor/lib64/lib-imsSDP.so:$(TARGET_COPY_OUT_VENDOR)/lib64/lib-imsSDP.so:lge \
    vendor/lge/bullhead/vendor/lib64/lib-imss.so:$(TARGET_COPY_OUT_VENDOR)/lib64/lib-imss.so:lge \
    vendor/lge/bullhead/vendor/lib64/lib-imsvt.so:$(TARGET_COPY_OUT_VENDOR)/lib64/lib-imsvt.so:lge \
    vendor/lge/bullhead/vendor/lib64/lib-imsxml.so:$(TARGET_COPY_OUT_VENDOR)/lib64/lib-imsxml.so:lge \
    vendor/lge/bullhead/vendor/lib64/libizat_core.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libizat_core.so:lge \
    vendor/lge/bullhead/vendor/lib64/libkmcrypto.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libkmcrypto.so:lge \
    vendor/lge/bullhead/vendor/lib64/liblbs_core.so:$(TARGET_COPY_OUT_VENDOR)/lib64/liblbs_core.so:lge \
    vendor/lge/bullhead/vendor/lib64/liblistensoundmodel2.so:$(TARGET_COPY_OUT_VENDOR)/lib64/liblistensoundmodel2.so:lge \
    vendor/lge/bullhead/vendor/lib64/libllvm-glnext.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libllvm-glnext.so:lge \
    vendor/lge/bullhead/vendor/lib64/libllvm-qcom.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libllvm-qcom.so:lge \
    vendor/lge/bullhead/vendor/lib64/libllvm-qgl.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libllvm-qgl.so:lge \
    vendor/lge/bullhead/vendor/lib64/liblowi_client.so:$(TARGET_COPY_OUT_VENDOR)/lib64/liblowi_client.so:lge \
    vendor/lge/bullhead/vendor/lib64/liblowi_wifihal_nl.so:$(TARGET_COPY_OUT_VENDOR)/lib64/liblowi_wifihal_nl.so:lge \
    vendor/lge/bullhead/vendor/lib64/liblowi_wifihal.so:$(TARGET_COPY_OUT_VENDOR)/lib64/liblowi_wifihal.so:lge \
    vendor/lge/bullhead/vendor/lib64/liblqe.so:$(TARGET_COPY_OUT_VENDOR)/lib64/liblqe.so:lge \
    vendor/lge/bullhead/vendor/lib64/libmdmdetect.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libmdmdetect.so:lge \
    vendor/lge/bullhead/vendor/lib64/libmdsprpc.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libmdsprpc.so:lge \
    vendor/lge/bullhead/vendor/lib64/libmmcamera2_q3a_core.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libmmcamera2_q3a_core.so:lge \
    vendor/lge/bullhead/vendor/lib64/libmmcamera2_stats_algorithm.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libmmcamera2_stats_algorithm.so:lge \
    vendor/lge/bullhead/vendor/lib64/libnetmgr.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libnetmgr.so:lge \
    vendor/lge/bullhead/vendor/lib64/libperipheral_client.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libperipheral_client.so:lge \
    vendor/lge/bullhead/vendor/lib64/libqcci_legacy.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libqcci_legacy.so:lge \
    vendor/lge/bullhead/vendor/lib64/libqdi.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libqdi.so:lge \
    vendor/lge/bullhead/vendor/lib64/libqdp.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libqdp.so:lge \
    vendor/lge/bullhead/vendor/lib64/libqmi_client_helper.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libqmi_client_helper.so:lge \
    vendor/lge/bullhead/vendor/lib64/libqmi_client_qmux.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libqmi_client_qmux.so:lge \
    vendor/lge/bullhead/vendor/lib64/libqmi_encdec.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libqmi_encdec.so:lge \
    vendor/lge/bullhead/vendor/lib64/libqmi.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libqmi.so:lge \
    vendor/lge/bullhead/vendor/lib64/libQSEEComAPI.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libQSEEComAPI.so:lge \
    vendor/lge/bullhead/vendor/lib64/libqti-perfd-client.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libqti-perfd-client.so:lge \
    vendor/lge/bullhead/vendor/lib64/libquipc_os_api.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libquipc_os_api.so:lge \
    vendor/lge/bullhead/vendor/lib64/lib-rcsimssjni.so:$(TARGET_COPY_OUT_VENDOR)/lib64/lib-rcsimssjni.so:lge \
    vendor/lge/bullhead/vendor/lib64/lib-rcsjni.so:$(TARGET_COPY_OUT_VENDOR)/lib64/lib-rcsjni.so:lge \
    vendor/lge/bullhead/vendor/lib64/libril-qc-qmi-1.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libril-qc-qmi-1.so:lge \
    vendor/lge/bullhead/vendor/lib64/libril-qcril-hook-oem.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libril-qcril-hook-oem.so:lge \
    vendor/lge/bullhead/vendor/lib64/librpmb.so:$(TARGET_COPY_OUT_VENDOR)/lib64/librpmb.so:lge \
    vendor/lge/bullhead/vendor/lib64/librs_adreno_sha1.so:$(TARGET_COPY_OUT_VENDOR)/lib64/librs_adreno_sha1.so:lge \
    vendor/lge/bullhead/vendor/lib64/librs_adreno.so:$(TARGET_COPY_OUT_VENDOR)/lib64/librs_adreno.so:lge \
    vendor/lge/bullhead/vendor/lib64/libRSDriver_adreno.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libRSDriver_adreno.so:lge \
    vendor/lge/bullhead/vendor/lib64/lib-rtpcommon.so:$(TARGET_COPY_OUT_VENDOR)/lib64/lib-rtpcommon.so:lge \
    vendor/lge/bullhead/vendor/lib64/lib-rtpcore.so:$(TARGET_COPY_OUT_VENDOR)/lib64/lib-rtpcore.so:lge \
    vendor/lge/bullhead/vendor/lib64/lib-rtpdaemoninterface.so:$(TARGET_COPY_OUT_VENDOR)/lib64/lib-rtpdaemoninterface.so:lge \
    vendor/lge/bullhead/vendor/lib64/lib-rtpsl.so:$(TARGET_COPY_OUT_VENDOR)/lib64/lib-rtpsl.so:lge \
    vendor/lge/bullhead/vendor/lib64/libscale.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libscale.so:lge \
    vendor/lge/bullhead/vendor/lib64/libsmemlog.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libsmemlog.so:lge \
    vendor/lge/bullhead/vendor/lib64/libssd.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libssd.so:lge \
    vendor/lge/bullhead/vendor/lib64/libsystem_health_mon.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libsystem_health_mon.so:lge \
    vendor/lge/bullhead/vendor/lib64/libthermalclient.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libthermalclient.so:lge \
    vendor/lge/bullhead/vendor/lib64/libthermalioctl.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libthermalioctl.so:lge \
    vendor/lge/bullhead/vendor/lib64/libtime_genoff.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libtime_genoff.so:lge \
    vendor/lge/bullhead/vendor/lib64/libTimeService.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libTimeService.so:lge \
    vendor/lge/bullhead/vendor/lib64/libtzdrmgenprov.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libtzdrmgenprov.so:lge \
    vendor/lge/bullhead/vendor/lib64/libvcel.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libvcel.so:lge \
    vendor/lge/bullhead/vendor/lib64/libvoice-svc.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libvoice-svc.so:lge \
    vendor/lge/bullhead/vendor/lib64/libvss_nv_core.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libvss_nv_core.so:lge \
    vendor/lge/bullhead/vendor/lib64/libvss_nv_idl.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libvss_nv_idl.so:lge \
    vendor/lge/bullhead/vendor/lib64/libvss_nv_iface.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libvss_nv_iface.so:lge \
    vendor/lge/bullhead/vendor/lib64/libwms.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libwms.so:lge \
    vendor/lge/bullhead/vendor/lib64/libxml.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libxml.so:lge \
    vendor/lge/bullhead/vendor/lib64/mediadrm/libdrmclearkeyplugin.so:$(TARGET_COPY_OUT_VENDOR)/lib64/mediadrm/libdrmclearkeyplugin.so:lge \
    vendor/lge/bullhead/vendor/lib/drm/libdrmwvmplugin.so:$(TARGET_COPY_OUT_VENDOR)/lib/drm/libdrmwvmplugin.so:lge \
    vendor/lge/bullhead/vendor/lib/egl/eglSubDriverAndroid.so:$(TARGET_COPY_OUT_VENDOR)/lib/egl/eglSubDriverAndroid.so:lge \
    vendor/lge/bullhead/vendor/lib/egl/libEGL_adreno.so:$(TARGET_COPY_OUT_VENDOR)/lib/egl/libEGL_adreno.so:lge \
    vendor/lge/bullhead/vendor/lib/egl/libGLESv1_CM_adreno.so:$(TARGET_COPY_OUT_VENDOR)/lib/egl/libGLESv1_CM_adreno.so:lge \
    vendor/lge/bullhead/vendor/lib/egl/libGLESv2_adreno.so:$(TARGET_COPY_OUT_VENDOR)/lib/egl/libGLESv2_adreno.so:lge \
    vendor/lge/bullhead/vendor/lib/egl/libq3dtools_adreno.so:$(TARGET_COPY_OUT_VENDOR)/lib/egl/libq3dtools_adreno.so:lge \
    vendor/lge/bullhead/vendor/lib/egl/libq3dtools_esx.so:$(TARGET_COPY_OUT_VENDOR)/lib/egl/libq3dtools_esx.so:lge \
    vendor/lge/bullhead/vendor/lib/hw/gatekeeper.msm8992.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/gatekeeper.msm8992.so:lge \
    vendor/lge/bullhead/vendor/lib/hw/keystore.msm8992.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/keystore.msm8992.so:lge \
    vendor/lge/bullhead/vendor/lib/hw/sound_trigger.primary.msm8992.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/sound_trigger.primary.msm8992.so:lge \
    vendor/lge/bullhead/vendor/lib/hw/tof.vl6180.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/tof.vl6180.so:lge \
    vendor/lge/bullhead/vendor/lib/hw/vulkan.msm8992.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/vulkan.msm8992.so:lge \
    vendor/lge/bullhead/vendor/lib/libacdb-fts.so:$(TARGET_COPY_OUT_VENDOR)/lib/libacdb-fts.so:lge \
    vendor/lge/bullhead/vendor/lib/libacdbloader.so:$(TARGET_COPY_OUT_VENDOR)/lib/libacdbloader.so:lge \
    vendor/lge/bullhead/vendor/lib/libacdbmapper.so:$(TARGET_COPY_OUT_VENDOR)/lib/libacdbmapper.so:lge \
    vendor/lge/bullhead/vendor/lib/libacdbrtac.so:$(TARGET_COPY_OUT_VENDOR)/lib/libacdbrtac.so:lge \
    vendor/lge/bullhead/vendor/lib/libactuator_lc898212xd_camcorder.so:$(TARGET_COPY_OUT_VENDOR)/lib/libactuator_lc898212xd_camcorder.so:lge \
    vendor/lge/bullhead/vendor/lib/libactuator_lc898212xd_camera.so:$(TARGET_COPY_OUT_VENDOR)/lib/libactuator_lc898212xd_camera.so:lge \
    vendor/lge/bullhead/vendor/lib/libactuator_lc898212xd.so:$(TARGET_COPY_OUT_VENDOR)/lib/libactuator_lc898212xd.so:lge \
    vendor/lge/bullhead/vendor/lib/libadiertac.so:$(TARGET_COPY_OUT_VENDOR)/lib/libadiertac.so:lge \
    vendor/lge/bullhead/vendor/lib/libadm.so:$(TARGET_COPY_OUT_VENDOR)/lib/libadm.so:lge \
    vendor/lge/bullhead/vendor/lib/libadpcmdec.so:$(TARGET_COPY_OUT_VENDOR)/lib/libadpcmdec.so:lge \
    vendor/lge/bullhead/vendor/lib/libadreno_utils.so:$(TARGET_COPY_OUT_VENDOR)/lib/libadreno_utils.so:lge \
    vendor/lge/bullhead/vendor/lib/libadsprpc.so:$(TARGET_COPY_OUT_VENDOR)/lib/libadsprpc.so:lge \
    vendor/lge/bullhead/vendor/lib/libaudcal.so:$(TARGET_COPY_OUT_VENDOR)/lib/libaudcal.so:lge \
    vendor/lge/bullhead/vendor/lib/libaudioalsa.so:$(TARGET_COPY_OUT_VENDOR)/lib/libaudioalsa.so:lge \
    vendor/lge/bullhead/vendor/lib/libbccQTI.so:$(TARGET_COPY_OUT_VENDOR)/lib/libbccQTI.so:lge \
    vendor/lge/bullhead/vendor/lib/libbtnv.so:$(TARGET_COPY_OUT_VENDOR)/lib/libbtnv.so:lge \
    vendor/lge/bullhead/vendor/lib/libC2D2.so:$(TARGET_COPY_OUT_VENDOR)/lib/libC2D2.so:lge \
    vendor/lge/bullhead/vendor/lib/libc2d30-a3xx.so:$(TARGET_COPY_OUT_VENDOR)/lib/libc2d30-a3xx.so:lge \
    vendor/lge/bullhead/vendor/lib/libc2d30-a4xx.so:$(TARGET_COPY_OUT_VENDOR)/lib/libc2d30-a4xx.so:lge \
    vendor/lge/bullhead/vendor/lib/libCB.so:$(TARGET_COPY_OUT_VENDOR)/lib/libCB.so:lge \
    vendor/lge/bullhead/vendor/lib/libchromatix_imx377_common.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx377_common.so:lge \
    vendor/lge/bullhead/vendor/lib/libchromatix_imx377_cpp_hfr_120.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx377_cpp_hfr_120.so:lge \
    vendor/lge/bullhead/vendor/lib/libchromatix_imx377_cpp_hfr_240.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx377_cpp_hfr_240.so:lge \
    vendor/lge/bullhead/vendor/lib/libchromatix_imx377_cpp_hfr_60.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx377_cpp_hfr_60.so:lge \
    vendor/lge/bullhead/vendor/lib/libchromatix_imx377_cpp_hfr_90.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx377_cpp_hfr_90.so:lge \
    vendor/lge/bullhead/vendor/lib/libchromatix_imx377_cpp_liveshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx377_cpp_liveshot.so:lge \
    vendor/lge/bullhead/vendor/lib/libchromatix_imx377_cpp_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx377_cpp_preview.so:lge \
    vendor/lge/bullhead/vendor/lib/libchromatix_imx377_cpp_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx377_cpp_snapshot.so:lge \
    vendor/lge/bullhead/vendor/lib/libchromatix_imx377_cpp_uhd_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx377_cpp_uhd_video.so:lge \
    vendor/lge/bullhead/vendor/lib/libchromatix_imx377_cpp_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx377_cpp_video.so:lge \
    vendor/lge/bullhead/vendor/lib/libchromatix_imx377_default_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx377_default_video.so:lge \
    vendor/lge/bullhead/vendor/lib/libchromatix_imx377_hfr_120.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx377_hfr_120.so:lge \
    vendor/lge/bullhead/vendor/lib/libchromatix_imx377_hfr_240.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx377_hfr_240.so:lge \
    vendor/lge/bullhead/vendor/lib/libchromatix_imx377_hfr_60.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx377_hfr_60.so:lge \
    vendor/lge/bullhead/vendor/lib/libchromatix_imx377_hfr_90.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx377_hfr_90.so:lge \
    vendor/lge/bullhead/vendor/lib/libchromatix_imx377_liveshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx377_liveshot.so:lge \
    vendor/lge/bullhead/vendor/lib/libchromatix_imx377_postproc.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx377_postproc.so:lge \
    vendor/lge/bullhead/vendor/lib/libchromatix_imx377_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx377_preview.so:lge \
    vendor/lge/bullhead/vendor/lib/libchromatix_imx377_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx377_snapshot.so:lge \
    vendor/lge/bullhead/vendor/lib/libchromatix_ov5693_common.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov5693_common.so:lge \
    vendor/lge/bullhead/vendor/lib/libchromatix_ov5693_cpp_liveshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov5693_cpp_liveshot.so:lge \
    vendor/lge/bullhead/vendor/lib/libchromatix_ov5693_cpp_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov5693_cpp_preview.so:lge \
    vendor/lge/bullhead/vendor/lib/libchromatix_ov5693_cpp_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov5693_cpp_snapshot.so:lge \
    vendor/lge/bullhead/vendor/lib/libchromatix_ov5693_cpp_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov5693_cpp_video.so:lge \
    vendor/lge/bullhead/vendor/lib/libchromatix_ov5693_default_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov5693_default_video.so:lge \
    vendor/lge/bullhead/vendor/lib/libchromatix_ov5693_liveshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov5693_liveshot.so:lge \
    vendor/lge/bullhead/vendor/lib/libchromatix_ov5693_postproc.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov5693_postproc.so:lge \
    vendor/lge/bullhead/vendor/lib/libchromatix_ov5693_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov5693_snapshot.so:lge \
    vendor/lge/bullhead/vendor/lib/libcneapiclient.so:$(TARGET_COPY_OUT_VENDOR)/lib/libcneapiclient.so:lge \
    vendor/lge/bullhead/vendor/lib/libcne.so:$(TARGET_COPY_OUT_VENDOR)/lib/libcne.so:lge \
    vendor/lge/bullhead/vendor/lib/libconfigdb.so:$(TARGET_COPY_OUT_VENDOR)/lib/libconfigdb.so:lge \
    vendor/lge/bullhead/vendor/lib/libdiag.so:$(TARGET_COPY_OUT_VENDOR)/lib/libdiag.so:lge \
    vendor/lge/bullhead/vendor/lib/lib-dplmedia.so:$(TARGET_COPY_OUT_VENDOR)/lib/lib-dplmedia.so:lge \
    vendor/lge/bullhead/vendor/lib/libdrmdecrypt.so:$(TARGET_COPY_OUT_VENDOR)/lib/libdrmdecrypt.so:lge \
    vendor/lge/bullhead/vendor/lib/libdrmfs.so:$(TARGET_COPY_OUT_VENDOR)/lib/libdrmfs.so:lge \
    vendor/lge/bullhead/vendor/lib/libdrmtime.so:$(TARGET_COPY_OUT_VENDOR)/lib/libdrmtime.so:lge \
    vendor/lge/bullhead/vendor/lib/libdsutils.so:$(TARGET_COPY_OUT_VENDOR)/lib/libdsutils.so:lge \
    vendor/lge/bullhead/vendor/lib/libfastcvopt.so:$(TARGET_COPY_OUT_VENDOR)/lib/libfastcvopt.so:lge \
    vendor/lge/bullhead/vendor/lib/libflash_pmic.so:$(TARGET_COPY_OUT_VENDOR)/lib/libflash_pmic.so:lge \
    vendor/lge/bullhead/vendor/lib/libfrsdk.so:$(TARGET_COPY_OUT_VENDOR)/lib/libfrsdk.so:lge \
    vendor/lge/bullhead/vendor/lib/libgcam_ae.so:$(TARGET_COPY_OUT_VENDOR)/lib/libgcam_ae.so:lge \
    vendor/lge/bullhead/vendor/lib/libgoog_eis_armeabi-v7a.so:$(TARGET_COPY_OUT_VENDOR)/lib/libgoog_eis_armeabi-v7a.so:lge \
    vendor/lge/bullhead/vendor/lib/libgoog_rownr.so:$(TARGET_COPY_OUT_VENDOR)/lib/libgoog_rownr.so:lge \
    vendor/lge/bullhead/vendor/lib/libgsl.so:$(TARGET_COPY_OUT_VENDOR)/lib/libgsl.so:lge \
    vendor/lge/bullhead/vendor/lib/libidl.so:$(TARGET_COPY_OUT_VENDOR)/lib/libidl.so:lge \
    vendor/lge/bullhead/vendor/lib/libimscamera_jni.so:$(TARGET_COPY_OUT_VENDOR)/lib/libimscamera_jni.so:lge \
    vendor/lge/bullhead/vendor/lib/lib-imsdpl.so:$(TARGET_COPY_OUT_VENDOR)/lib/lib-imsdpl.so:lge \
    vendor/lge/bullhead/vendor/lib/libimsmedia_jni.so:$(TARGET_COPY_OUT_VENDOR)/lib/libimsmedia_jni.so:lge \
    vendor/lge/bullhead/vendor/lib/lib-imsqimf.so:$(TARGET_COPY_OUT_VENDOR)/lib/lib-imsqimf.so:lge \
    vendor/lge/bullhead/vendor/lib/lib-imsrcscmclient.so:$(TARGET_COPY_OUT_VENDOR)/lib/lib-imsrcscmclient.so:lge \
    vendor/lge/bullhead/vendor/lib/lib-ims-rcscmjni.so:$(TARGET_COPY_OUT_VENDOR)/lib/lib-ims-rcscmjni.so:lge \
    vendor/lge/bullhead/vendor/lib/lib-imsrcscmservice.so:$(TARGET_COPY_OUT_VENDOR)/lib/lib-imsrcscmservice.so:lge \
    vendor/lge/bullhead/vendor/lib/lib-imsrcscm.so:$(TARGET_COPY_OUT_VENDOR)/lib/lib-imsrcscm.so:lge \
    vendor/lge/bullhead/vendor/lib/lib-imsrcs.so:$(TARGET_COPY_OUT_VENDOR)/lib/lib-imsrcs.so:lge \
    vendor/lge/bullhead/vendor/lib/lib-imsSDP.so:$(TARGET_COPY_OUT_VENDOR)/lib/lib-imsSDP.so:lge \
    vendor/lge/bullhead/vendor/lib/lib-imss.so:$(TARGET_COPY_OUT_VENDOR)/lib/lib-imss.so:lge \
    vendor/lge/bullhead/vendor/lib/lib-imsvt.so:$(TARGET_COPY_OUT_VENDOR)/lib/lib-imsvt.so:lge \
    vendor/lge/bullhead/vendor/lib/lib-imsxml.so:$(TARGET_COPY_OUT_VENDOR)/lib/lib-imsxml.so:lge \
    vendor/lge/bullhead/vendor/lib/libjpegdhw.so:$(TARGET_COPY_OUT_VENDOR)/lib/libjpegdhw.so:lge \
    vendor/lge/bullhead/vendor/lib/libjpegdmahw.so:$(TARGET_COPY_OUT_VENDOR)/lib/libjpegdmahw.so:lge \
    vendor/lge/bullhead/vendor/lib/libjpegehw.so:$(TARGET_COPY_OUT_VENDOR)/lib/libjpegehw.so:lge \
    vendor/lge/bullhead/vendor/lib/libkmcrypto.so:$(TARGET_COPY_OUT_VENDOR)/lib/libkmcrypto.so:lge \
    vendor/lge/bullhead/vendor/lib/liblistensoundmodel2.so:$(TARGET_COPY_OUT_VENDOR)/lib/liblistensoundmodel2.so:lge \
    vendor/lge/bullhead/vendor/lib/libllvm-glnext.so:$(TARGET_COPY_OUT_VENDOR)/lib/libllvm-glnext.so:lge \
    vendor/lge/bullhead/vendor/lib/libllvm-qcom.so:$(TARGET_COPY_OUT_VENDOR)/lib/libllvm-qcom.so:lge \
    vendor/lge/bullhead/vendor/lib/libllvm-qgl.so:$(TARGET_COPY_OUT_VENDOR)/lib/libllvm-qgl.so:lge \
    vendor/lge/bullhead/vendor/lib/liblqe.so:$(TARGET_COPY_OUT_VENDOR)/lib/liblqe.so:lge \
    vendor/lge/bullhead/vendor/lib/libmdmdetect.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmdmdetect.so:lge \
    vendor/lge/bullhead/vendor/lib/libmdsprpc.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmdsprpc.so:lge \
    vendor/lge/bullhead/vendor/lib/libmmcamera2_c2d_module.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera2_c2d_module.so:lge \
    vendor/lge/bullhead/vendor/lib/libmmcamera2_cpp_module.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera2_cpp_module.so:lge \
    vendor/lge/bullhead/vendor/lib/libmmcamera2_frame_algorithm.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera2_frame_algorithm.so:lge \
    vendor/lge/bullhead/vendor/lib/libmmcamera2_iface_modules.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera2_iface_modules.so:lge \
    vendor/lge/bullhead/vendor/lib/libmmcamera2_imglib_modules.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera2_imglib_modules.so:lge \
    vendor/lge/bullhead/vendor/lib/libmmcamera2_isp_modules.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera2_isp_modules.so:lge \
    vendor/lge/bullhead/vendor/lib/libmmcamera2_is.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera2_is.so:lge \
    vendor/lge/bullhead/vendor/lib/libmmcamera2_pp_buf_mgr.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera2_pp_buf_mgr.so:lge \
    vendor/lge/bullhead/vendor/lib/libmmcamera2_pproc_modules.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera2_pproc_modules.so:lge \
    vendor/lge/bullhead/vendor/lib/libmmcamera2_q3a_core.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera2_q3a_core.so:lge \
    vendor/lge/bullhead/vendor/lib/libmmcamera2_sensor_debug.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera2_sensor_debug.so:lge \
    vendor/lge/bullhead/vendor/lib/libmmcamera2_sensor_modules.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera2_sensor_modules.so:lge \
    vendor/lge/bullhead/vendor/lib/libmmcamera2_stats_algorithm.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera2_stats_algorithm.so:lge \
    vendor/lge/bullhead/vendor/lib/libmmcamera2_stats_modules.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera2_stats_modules.so:lge \
    vendor/lge/bullhead/vendor/lib/libmmcamera2_vpe_module.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera2_vpe_module.so:lge \
    vendor/lge/bullhead/vendor/lib/libmmcamera2_wnr_module.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera2_wnr_module.so:lge \
    vendor/lge/bullhead/vendor/lib/libmmcamera_brcb032gwz_eeprom.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_brcb032gwz_eeprom.so:lge \
    vendor/lge/bullhead/vendor/lib/libmmcamera_cac2_lib.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_cac2_lib.so:lge \
    vendor/lge/bullhead/vendor/lib/libmmcamera_dummyalgo.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_dummyalgo.so:lge \
    vendor/lge/bullhead/vendor/lib/libmmcamera_eebinparse.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_eebinparse.so:lge \
    vendor/lge/bullhead/vendor/lib/libmmcamera_eeprom_util.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_eeprom_util.so:lge \
    vendor/lge/bullhead/vendor/lib/libmmcamera_eztune_module.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_eztune_module.so:lge \
    vendor/lge/bullhead/vendor/lib/libmmcamera_faceproc.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_faceproc.so:lge \
    vendor/lge/bullhead/vendor/lib/libmmcamera_imglib.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_imglib.so:lge \
    vendor/lge/bullhead/vendor/lib/libmmcamera_imx377.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_imx377.so:lge \
    vendor/lge/bullhead/vendor/lib/libmmcamera_isp_abcc44.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_isp_abcc44.so:lge \
    vendor/lge/bullhead/vendor/lib/libmmcamera_isp_abf44.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_isp_abf44.so:lge \
    vendor/lge/bullhead/vendor/lib/libmmcamera_isp_bcc44.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_isp_bcc44.so:lge \
    vendor/lge/bullhead/vendor/lib/libmmcamera_isp_be_stats44.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_isp_be_stats44.so:lge \
    vendor/lge/bullhead/vendor/lib/libmmcamera_isp_bf_scale_stats44.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_isp_bf_scale_stats44.so:lge \
    vendor/lge/bullhead/vendor/lib/libmmcamera_isp_bf_stats44.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_isp_bf_stats44.so:lge \
    vendor/lge/bullhead/vendor/lib/libmmcamera_isp_bg_stats44.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_isp_bg_stats44.so:lge \
    vendor/lge/bullhead/vendor/lib/libmmcamera_isp_bhist_stats44.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_isp_bhist_stats44.so:lge \
    vendor/lge/bullhead/vendor/lib/libmmcamera_isp_bpc44.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_isp_bpc44.so:lge \
    vendor/lge/bullhead/vendor/lib/libmmcamera_isp_chroma_enhan40.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_isp_chroma_enhan40.so:lge \
    vendor/lge/bullhead/vendor/lib/libmmcamera_isp_chroma_suppress40.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_isp_chroma_suppress40.so:lge \
    vendor/lge/bullhead/vendor/lib/libmmcamera_isp_clamp_encoder40.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_isp_clamp_encoder40.so:lge \
    vendor/lge/bullhead/vendor/lib/libmmcamera_isp_clamp_video40.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_isp_clamp_video40.so:lge \
    vendor/lge/bullhead/vendor/lib/libmmcamera_isp_clamp_viewfinder40.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_isp_clamp_viewfinder40.so:lge \
    vendor/lge/bullhead/vendor/lib/libmmcamera_isp_clf44.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_isp_clf44.so:lge \
    vendor/lge/bullhead/vendor/lib/libmmcamera_isp_color_correct40.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_isp_color_correct40.so:lge \
    vendor/lge/bullhead/vendor/lib/libmmcamera_isp_color_xform_encoder40.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_isp_color_xform_encoder40.so:lge \
    vendor/lge/bullhead/vendor/lib/libmmcamera_isp_color_xform_viewfinder40.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_isp_color_xform_viewfinder40.so:lge \
    vendor/lge/bullhead/vendor/lib/libmmcamera_isp_cs_stats44.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_isp_cs_stats44.so:lge \
    vendor/lge/bullhead/vendor/lib/libmmcamera_isp_demosaic44.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_isp_demosaic44.so:lge \
    vendor/lge/bullhead/vendor/lib/libmmcamera_isp_demux40.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_isp_demux40.so:lge \
    vendor/lge/bullhead/vendor/lib/libmmcamera_isp_fovcrop_encoder40.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_isp_fovcrop_encoder40.so:lge \
    vendor/lge/bullhead/vendor/lib/libmmcamera_isp_fovcrop_viewfinder40.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_isp_fovcrop_viewfinder40.so:lge \
    vendor/lge/bullhead/vendor/lib/libmmcamera_isp_gamma44.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_isp_gamma44.so:lge \
    vendor/lge/bullhead/vendor/lib/libmmcamera_isp_ihist_stats44.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_isp_ihist_stats44.so:lge \
    vendor/lge/bullhead/vendor/lib/libmmcamera_isp_linearization40.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_isp_linearization40.so:lge \
    vendor/lge/bullhead/vendor/lib/libmmcamera_isp_ltm44.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_isp_ltm44.so:lge \
    vendor/lge/bullhead/vendor/lib/libmmcamera_isp_luma_adaptation40.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_isp_luma_adaptation40.so:lge \
    vendor/lge/bullhead/vendor/lib/libmmcamera_isp_mce40.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_isp_mce40.so:lge \
    vendor/lge/bullhead/vendor/lib/libmmcamera_isp_mesh_rolloff44.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_isp_mesh_rolloff44.so:lge \
    vendor/lge/bullhead/vendor/lib/libmmcamera_isp_rs_stats44.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_isp_rs_stats44.so:lge \
    vendor/lge/bullhead/vendor/lib/libmmcamera_isp_scaler_encoder44.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_isp_scaler_encoder44.so:lge \
    vendor/lge/bullhead/vendor/lib/libmmcamera_isp_scaler_viewfinder44.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_isp_scaler_viewfinder44.so:lge \
    vendor/lge/bullhead/vendor/lib/libmmcamera_isp_sce40.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_isp_sce40.so:lge \
    vendor/lge/bullhead/vendor/lib/libmmcamera_isp_sub_module.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_isp_sub_module.so:lge \
    vendor/lge/bullhead/vendor/lib/libmmcamera_isp_wb40.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_isp_wb40.so:lge \
    vendor/lge/bullhead/vendor/lib/libmmcamera_m24c64s_eeprom.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_m24c64s_eeprom.so:lge \
    vendor/lge/bullhead/vendor/lib/libmmcamera_ov5693.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_ov5693.so:lge \
    vendor/lge/bullhead/vendor/lib/libmmcamera_pdafcamif.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_pdafcamif.so:lge \
    vendor/lge/bullhead/vendor/lib/libmmcamera_pdaf.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_pdaf.so:lge \
    vendor/lge/bullhead/vendor/lib/libmmcamera_ppbase_module.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_ppbase_module.so:lge \
    vendor/lge/bullhead/vendor/lib/libmmcamera_tintless_algo.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_tintless_algo.so:lge \
    vendor/lge/bullhead/vendor/lib/libmmcamera_tintless_bg_pca_algo.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_tintless_bg_pca_algo.so:lge \
    vendor/lge/bullhead/vendor/lib/libmmcamera_vpu_module.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_vpu_module.so:lge \
    vendor/lge/bullhead/vendor/lib/libmmipl.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmipl.so:lge \
    vendor/lge/bullhead/vendor/lib/libmmjpeg.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmjpeg.so:lge \
    vendor/lge/bullhead/vendor/lib/libmmqjpeg_codec.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmqjpeg_codec.so:lge \
    vendor/lge/bullhead/vendor/lib/libmmqjpegdma.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmqjpegdma.so:lge \
    vendor/lge/bullhead/vendor/lib/libnetmgr.so:$(TARGET_COPY_OUT_VENDOR)/lib/libnetmgr.so:lge \
    vendor/lge/bullhead/vendor/lib/liboemcamera.so:$(TARGET_COPY_OUT_VENDOR)/lib/liboemcamera.so:lge \
    vendor/lge/bullhead/vendor/lib/liboemcrypto.so:$(TARGET_COPY_OUT_VENDOR)/lib/liboemcrypto.so:lge \
    vendor/lge/bullhead/vendor/lib/libperipheral_client.so:$(TARGET_COPY_OUT_VENDOR)/lib/libperipheral_client.so:lge \
    vendor/lge/bullhead/vendor/lib/libqcci_legacy.so:$(TARGET_COPY_OUT_VENDOR)/lib/libqcci_legacy.so:lge \
    vendor/lge/bullhead/vendor/lib/libqdi.so:$(TARGET_COPY_OUT_VENDOR)/lib/libqdi.so:lge \
    vendor/lge/bullhead/vendor/lib/libqdp.so:$(TARGET_COPY_OUT_VENDOR)/lib/libqdp.so:lge \
    vendor/lge/bullhead/vendor/lib/libqmi_client_helper.so:$(TARGET_COPY_OUT_VENDOR)/lib/libqmi_client_helper.so:lge \
    vendor/lge/bullhead/vendor/lib/libqmi_client_qmux.so:$(TARGET_COPY_OUT_VENDOR)/lib/libqmi_client_qmux.so:lge \
    vendor/lge/bullhead/vendor/lib/libqmi_encdec.so:$(TARGET_COPY_OUT_VENDOR)/lib/libqmi_encdec.so:lge \
    vendor/lge/bullhead/vendor/lib/libqmi.so:$(TARGET_COPY_OUT_VENDOR)/lib/libqmi.so:lge \
    vendor/lge/bullhead/vendor/lib/libqomx_jpegdec.so:$(TARGET_COPY_OUT_VENDOR)/lib/libqomx_jpegdec.so:lge \
    vendor/lge/bullhead/vendor/lib/libqomx_jpegenc_pipe.so:$(TARGET_COPY_OUT_VENDOR)/lib/libqomx_jpegenc_pipe.so:lge \
    vendor/lge/bullhead/vendor/lib/libqomx_jpegenc.so:$(TARGET_COPY_OUT_VENDOR)/lib/libqomx_jpegenc.so:lge \
    vendor/lge/bullhead/vendor/lib/libQSEEComAPI.so:$(TARGET_COPY_OUT_VENDOR)/lib/libQSEEComAPI.so:lge \
    vendor/lge/bullhead/vendor/lib/libqti-perfd-client.so:$(TARGET_COPY_OUT_VENDOR)/lib/libqti-perfd-client.so:lge \
    vendor/lge/bullhead/vendor/lib/lib-rcsimssjni.so:$(TARGET_COPY_OUT_VENDOR)/lib/lib-rcsimssjni.so:lge \
    vendor/lge/bullhead/vendor/lib/lib-rcsjni.so:$(TARGET_COPY_OUT_VENDOR)/lib/lib-rcsjni.so:lge \
    vendor/lge/bullhead/vendor/lib/libril-qc-qmi-1.so:$(TARGET_COPY_OUT_VENDOR)/lib/libril-qc-qmi-1.so:lge \
    vendor/lge/bullhead/vendor/lib/libril-qcril-hook-oem.so:$(TARGET_COPY_OUT_VENDOR)/lib/libril-qcril-hook-oem.so:lge \
    vendor/lge/bullhead/vendor/lib/librpmb.so:$(TARGET_COPY_OUT_VENDOR)/lib/librpmb.so:lge \
    vendor/lge/bullhead/vendor/lib/librs_adreno_sha1.so:$(TARGET_COPY_OUT_VENDOR)/lib/librs_adreno_sha1.so:lge \
    vendor/lge/bullhead/vendor/lib/librs_adreno.so:$(TARGET_COPY_OUT_VENDOR)/lib/librs_adreno.so:lge \
    vendor/lge/bullhead/vendor/lib/libRSDriver_adreno.so:$(TARGET_COPY_OUT_VENDOR)/lib/libRSDriver_adreno.so:lge \
    vendor/lge/bullhead/vendor/lib/librs.rnr_downscale.so:$(TARGET_COPY_OUT_VENDOR)/lib/librs.rnr_downscale.so:lge \
    vendor/lge/bullhead/vendor/lib/librs.rnr_process.so:$(TARGET_COPY_OUT_VENDOR)/lib/librs.rnr_process.so:lge \
    vendor/lge/bullhead/vendor/lib/lib-rtpcommon.so:$(TARGET_COPY_OUT_VENDOR)/lib/lib-rtpcommon.so:lge \
    vendor/lge/bullhead/vendor/lib/lib-rtpcore.so:$(TARGET_COPY_OUT_VENDOR)/lib/lib-rtpcore.so:lge \
    vendor/lge/bullhead/vendor/lib/lib-rtpdaemoninterface.so:$(TARGET_COPY_OUT_VENDOR)/lib/lib-rtpdaemoninterface.so:lge \
    vendor/lge/bullhead/vendor/lib/lib-rtpsl.so:$(TARGET_COPY_OUT_VENDOR)/lib/lib-rtpsl.so:lge \
    vendor/lge/bullhead/vendor/lib/libscale.so:$(TARGET_COPY_OUT_VENDOR)/lib/libscale.so:lge \
    vendor/lge/bullhead/vendor/lib/libsmemlog.so:$(TARGET_COPY_OUT_VENDOR)/lib/libsmemlog.so:lge \
    vendor/lge/bullhead/vendor/lib/libssd.so:$(TARGET_COPY_OUT_VENDOR)/lib/libssd.so:lge \
    vendor/lge/bullhead/vendor/lib/libsystem_health_mon.so:$(TARGET_COPY_OUT_VENDOR)/lib/libsystem_health_mon.so:lge \
    vendor/lge/bullhead/vendor/lib/libthermalclient.so:$(TARGET_COPY_OUT_VENDOR)/lib/libthermalclient.so:lge \
    vendor/lge/bullhead/vendor/lib/libthermalioctl.so:$(TARGET_COPY_OUT_VENDOR)/lib/libthermalioctl.so:lge \
    vendor/lge/bullhead/vendor/lib/libtime_genoff.so:$(TARGET_COPY_OUT_VENDOR)/lib/libtime_genoff.so:lge \
    vendor/lge/bullhead/vendor/lib/libTimeService.so:$(TARGET_COPY_OUT_VENDOR)/lib/libTimeService.so:lge \
    vendor/lge/bullhead/vendor/lib/libtzdrmgenprov.so:$(TARGET_COPY_OUT_VENDOR)/lib/libtzdrmgenprov.so:lge \
    vendor/lge/bullhead/vendor/lib/libvcel.so:$(TARGET_COPY_OUT_VENDOR)/lib/libvcel.so:lge \
    vendor/lge/bullhead/vendor/lib/libvoice-svc.so:$(TARGET_COPY_OUT_VENDOR)/lib/libvoice-svc.so:lge \
    vendor/lge/bullhead/vendor/lib/libvss_nv_core.so:$(TARGET_COPY_OUT_VENDOR)/lib/libvss_nv_core.so:lge \
    vendor/lge/bullhead/vendor/lib/libvss_nv_idl.so:$(TARGET_COPY_OUT_VENDOR)/lib/libvss_nv_idl.so:lge \
    vendor/lge/bullhead/vendor/lib/libvss_nv_iface.so:$(TARGET_COPY_OUT_VENDOR)/lib/libvss_nv_iface.so:lge \
    vendor/lge/bullhead/vendor/lib/libwms.so:$(TARGET_COPY_OUT_VENDOR)/lib/libwms.so:lge \
    vendor/lge/bullhead/vendor/lib/libwvdrm_L1.so:$(TARGET_COPY_OUT_VENDOR)/lib/libwvdrm_L1.so:lge \
    vendor/lge/bullhead/vendor/lib/libwvm.so:$(TARGET_COPY_OUT_VENDOR)/lib/libwvm.so:lge \
    vendor/lge/bullhead/vendor/lib/libWVStreamControlAPI_L1.so:$(TARGET_COPY_OUT_VENDOR)/lib/libWVStreamControlAPI_L1.so:lge \
    vendor/lge/bullhead/vendor/lib/libxml.so:$(TARGET_COPY_OUT_VENDOR)/lib/libxml.so:lge \
    vendor/lge/bullhead/vendor/lib/mediadrm/libdrmclearkeyplugin.so:$(TARGET_COPY_OUT_VENDOR)/lib/mediadrm/libdrmclearkeyplugin.so:lge \
    vendor/lge/bullhead/vendor/lib/mediadrm/libwvdrmengine.so:$(TARGET_COPY_OUT_VENDOR)/lib/mediadrm/libwvdrmengine.so:lge \
    vendor/lge/bullhead/vendor/lib/rfsa/adsp/fastrpc_shell_0:$(TARGET_COPY_OUT_VENDOR)/lib/rfsa/adsp/fastrpc_shell_0:lge \
    vendor/lge/bullhead/vendor/media/LMspeed_508.emd:$(TARGET_COPY_OUT_VENDOR)/media/LMspeed_508.emd:lge \
    vendor/lge/bullhead/vendor/media/PFFprec_600.emd:$(TARGET_COPY_OUT_VENDOR)/media/PFFprec_600.emd:lge

